// Interupts EXTI Project

/**
  ******************************************************************************
  * @file    EXTI/stm32f10x_it.c 
  * @author  MCD Application Team
  * @version V1.0.0
  * @date    15/09/2010
  * @brief   Main Interrupt Service Routines.
  *          This file provides template for all exceptions handler and peripherals
  *          interrupt service routine.
  ******************************************************************************
  * @copy
  *
  * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
  * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
  * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
  * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
  * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
  * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
  *
  * <h2><center>&copy; COPYRIGHT 2010 STMicroelectronics</center></h2>
  */



/* Includes ------------------------------------------------------------------*/
#include "stm32f10x_it.h"
#include "string.h"

void Delay(vu32 nCount);
uint8_t stringCompare(char str1[],char str2[], uint8_t StrLength);
void TransmitData(void);
void process_gga_data(char* s);
void process_rmc_data(char* s);

extern char Receive_Buffer[];
extern char Transmit_Buffer[];
int receptionBlocked = 0; //blocks reception for Usart1

/** @addtogroup Examples
  * @{
  */


/* Private typedef -----------------------------------------------------------*/
/* Private define ------------------------------------------------------------*/
/* Private macro -------------------------------------------------------------*/
/* Private variables ---------------------------------------------------------*/
/* Private function prototypes -----------------------------------------------*/
/* Private functions ---------------------------------------------------------*/

/******************************************************************************/
/*            Cortex-M3 Processor Exceptions Handlers                         */
/******************************************************************************/

/**
  * @brief  This function handles NMI exception.
  * @param  None
  * @retval None
  */
void NMI_Handler(void)
{
}

/**
  * @brief  This function handles Hard Fault exception.
  * @param  None
  * @retval None
  */
void HardFault_Handler(void)
{
  /* Go to infinite loop when Hard Fault exception occurs */
  while (1)
  {
  }
}

/**
  * @brief  This function handles Memory Manage exception.
  * @param  None
  * @retval None
  */
void MemManage_Handler(void)
{
  /* Go to infinite loop when Memory Manage exception occurs */
  while (1)
  {
  }
}

/**
  * @brief  This function handles Bus Fault exception.
  * @param  None
  * @retval None
  */
void BusFault_Handler(void)
{
  /* Go to infinite loop when Bus Fault exception occurs */
  while (1)
  {
  }
}

/**
  * @brief  This function handles Usage Fault exception.
  * @param  None
  * @retval None
  */
void UsageFault_Handler(void)
{
  /* Go to infinite loop when Usage Fault exception occurs */
  while (1)
  {
  }
}

/**
  * @brief  This function handles SVCall exception.
  * @param  None
  * @retval None
  */
void SVC_Handler(void)
{
}

/**
  * @brief  This function handles Debug Monitor exception.
  * @param  None
  * @retval None
  */
void DebugMon_Handler(void)
{
}

/**
  * @brief  This function handles PendSV_Handler exception.
  * @param  None
  * @retval None
  */
void PendSV_Handler(void)
{
}

/**
  * @brief  This function handles SysTick Handler.
  * @param  None
  * @retval None
  */
void SysTick_Handler(void)
{
}

/******************************************************************************/
/*            STM32F10x Peripherals Interrupt Handlers                        */
/******************************************************************************/

/**
  * @brief  This function handles External line0 interrupt request.
  * @param  None
  * @retval None
  */

void EXTI15_10_IRQHandler(void)
{
    

	    // Check if the interrupt was generated by EXTI Line 13
    if (EXTI_GetITStatus(EXTI_Line13) != RESET)
    {
			// Button (PC13) is pressed, handle the button press
        TransmitData();	
				//enable DMA
			  DMA_Cmd(DMA1_Channel7, ENABLE);
        // Clear the interrupt flag
        EXTI_ClearITPendingBit(EXTI_Line13);

        		
    }
}

/******************************************************************************/
/*                 STM32F10x Peripherals Interrupt Handlers                   */
/*  Add here the Interrupt Handler for the used peripheral(s) (PPP), for the  */
/*  available peripheral interrupt handler's name please refer to the startup */
/*  file (startup_stm32f10x_xx.s).                                            */
/******************************************************************************/

/**
  * @brief  This function handles DMA interrupt requests.
  * @param  None
  * @retval None
  */

 
void DMA1_Channel5_IRQHandler(void)
{
  /* Test on DMAx Channely Transfer Half interrupt */
  if(DMA_GetITStatus(DMA1_IT_TC5))

    DMA_ClearITPendingBit(DMA1_IT_TC5);  
	
}


void DMA1_Channel7_IRQHandler(void)
{
  /* Test on DMAx Channely Transfer complete interrupt */
  if(DMA_GetITStatus(DMA1_IT_TC7))

    DMA_ClearITPendingBit(DMA1_IT_TC7);  
	  DMA_Cmd(DMA1_Channel7, DISABLE);
	
}




/**
  * @brief  This function handles USART1 RX interrupt requests.
  * @param  None
  * @retval None
  */

int txcount=0;


void TransmitData(void){
	// Process the GPS data (extract required information, etc.)
						if (strncmp(Receive_Buffer, "$GPGGA", 6) == 0) {
							strcpy( Transmit_Buffer ,"");
								// Process GGA sentence
								process_gga_data(Receive_Buffer);
							}
							// Check if the data starts with '$GPRMC' (for RMC sentence)
							else if (strncmp(Receive_Buffer, "$GPRMC", 6) == 0) {
								strcpy( Transmit_Buffer ,"");
								// Process RMC sentence
								process_rmc_data(Receive_Buffer);
							}
}

	void process_gga_data(char* s){
		int desired_fields[] = {2, 5, 6, 8, 10, 11};

    int c = 1;
    char *start = s;
    char *end = strchr(s, ',');
		 int i=0;
    while (end != NULL && i < 6) {
        if (c == desired_fields[i]) {
            strncat(Transmit_Buffer, start, end - start);
            strcat(Transmit_Buffer, ",");
						i++;
        }

        start = end + 1;
        end = strchr(start, ',');
				
        c++;
    }
     
}
	
	
	
void process_rmc_data(char* s){
		int desired_fields[] = {2, 3, 6, 7, 10};

    int c = 1;
    char *start = s;
    char *end = strchr(s, ',');
		 int i=0;
    while (end != NULL && i <= 6) {
        if (c == desired_fields[i]) {
            strncat(Transmit_Buffer, start, end - start);
            strcat(Transmit_Buffer, ",");
						i++;
        }

        start = end + 1;
        end = strchr(start, ',');
				
        c++;
    }
}

/******************* (C) COPYRIGHT 2010 STMicroelectronics *****END OF FILE****/
